[tool.poetry]
name = "swaglib"
version = "0.1.3"
description = "swaglib"
authors = ["nomaakip <nomaakip@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.25.1"  # Ensure this is included
